# Generated by Django 3.1.7 on 2021-09-16 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210914_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisonerprofile',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
    ]
